// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _413Project2.Models;

namespace _413Project2.Migrations
{
    [DbContext(typeof(ToursDbContext))]
    [Migration("20220323043018_NameUpdate3")]
    partial class NameUpdate3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("_413Project2.Models.AppointmentInfo", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeSlotsTimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.HasIndex("TimeSlotsTimeSlotId");

                    b.ToTable("AppointmentInfo");
                });

            modelBuilder.Entity("_413Project2.Models.TimeSlots", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeSlotAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlotName")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 8am"
                        },
                        new
                        {
                            TimeSlotId = 2,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 9am"
                        },
                        new
                        {
                            TimeSlotId = 3,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 10am"
                        },
                        new
                        {
                            TimeSlotId = 4,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 11am"
                        },
                        new
                        {
                            TimeSlotId = 5,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 6,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 7,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 8,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 9,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 10,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 11,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 12,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 13,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Monday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 14,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 8am"
                        },
                        new
                        {
                            TimeSlotId = 15,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 9am"
                        },
                        new
                        {
                            TimeSlotId = 16,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 10am"
                        },
                        new
                        {
                            TimeSlotId = 17,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 11am"
                        },
                        new
                        {
                            TimeSlotId = 18,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 19,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 20,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 21,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 22,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 23,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 24,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 25,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 26,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Tuesday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 27,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 8am"
                        },
                        new
                        {
                            TimeSlotId = 28,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 9am"
                        },
                        new
                        {
                            TimeSlotId = 29,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 10am"
                        },
                        new
                        {
                            TimeSlotId = 30,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 11am"
                        },
                        new
                        {
                            TimeSlotId = 31,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 32,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 33,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 34,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 35,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 36,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 37,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 38,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 39,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Wednesday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 40,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 8am"
                        },
                        new
                        {
                            TimeSlotId = 41,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 9am"
                        },
                        new
                        {
                            TimeSlotId = 42,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 10am"
                        },
                        new
                        {
                            TimeSlotId = 43,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 11am"
                        },
                        new
                        {
                            TimeSlotId = 44,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 45,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 46,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 47,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 48,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 49,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 50,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 51,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 52,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Thursday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 53,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 8am"
                        },
                        new
                        {
                            TimeSlotId = 54,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 9am"
                        },
                        new
                        {
                            TimeSlotId = 55,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 10am"
                        },
                        new
                        {
                            TimeSlotId = 56,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 11am"
                        },
                        new
                        {
                            TimeSlotId = 57,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 58,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 59,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 60,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 61,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 62,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 63,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 64,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 65,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Friday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 66,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 8am"
                        },
                        new
                        {
                            TimeSlotId = 67,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 9am"
                        },
                        new
                        {
                            TimeSlotId = 68,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 10am"
                        },
                        new
                        {
                            TimeSlotId = 69,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 11am"
                        },
                        new
                        {
                            TimeSlotId = 70,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 71,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 72,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 73,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 74,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 75,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 76,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 77,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 78,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Saturday 8pm"
                        },
                        new
                        {
                            TimeSlotId = 79,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 8am"
                        },
                        new
                        {
                            TimeSlotId = 80,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 9am"
                        },
                        new
                        {
                            TimeSlotId = 81,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 10am"
                        },
                        new
                        {
                            TimeSlotId = 82,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 11am"
                        },
                        new
                        {
                            TimeSlotId = 83,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 12pm"
                        },
                        new
                        {
                            TimeSlotId = 84,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 1pm"
                        },
                        new
                        {
                            TimeSlotId = 85,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 2pm"
                        },
                        new
                        {
                            TimeSlotId = 86,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 3pm"
                        },
                        new
                        {
                            TimeSlotId = 87,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 4pm"
                        },
                        new
                        {
                            TimeSlotId = 88,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 5pm"
                        },
                        new
                        {
                            TimeSlotId = 89,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 6pm"
                        },
                        new
                        {
                            TimeSlotId = 90,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 7pm"
                        },
                        new
                        {
                            TimeSlotId = 91,
                            TimeSlotAvailable = true,
                            TimeSlotName = "Sunday 8pm"
                        });
                });

            modelBuilder.Entity("_413Project2.Models.AppointmentInfo", b =>
                {
                    b.HasOne("_413Project2.Models.TimeSlots", "TimeSlots")
                        .WithMany()
                        .HasForeignKey("TimeSlotsTimeSlotId");
                });
#pragma warning restore 612, 618
        }
    }
}
