// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _413Project2.Models;

namespace _413Project2.Migrations
{
    [DbContext(typeof(ToursDbContext))]
    [Migration("20220322215027_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("_413Project2.Models.AppointmentInfo", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeSlotsTimeSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.HasIndex("TimeSlotsTimeSlotId");

                    b.ToTable("AppointmentInfo");
                });

            modelBuilder.Entity("_413Project2.Models.TimeSlots", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeSlotAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 2,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 3,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 4,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 5,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 6,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 7,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 8,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 9,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 10,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 11,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 12,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 13,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 14,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 15,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 16,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 17,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 18,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 19,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 20,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 21,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 22,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 23,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 24,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 25,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 26,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 27,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 28,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 29,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 30,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 31,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 32,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 33,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 34,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 35,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 36,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 37,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 38,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 39,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 40,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 41,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 42,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 43,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 44,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 45,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 46,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 47,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 48,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 49,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 50,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 51,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 52,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 53,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 54,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 55,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 56,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 57,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 58,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 59,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 60,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 61,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 62,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 63,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 64,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 65,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 66,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 67,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 68,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 69,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 70,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 71,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 72,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 73,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 74,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 75,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 76,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 77,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 78,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 79,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 80,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 81,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 82,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 83,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 84,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 85,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 86,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 87,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 88,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 89,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 90,
                            TimeSlotAvailable = true
                        },
                        new
                        {
                            TimeSlotId = 91,
                            TimeSlotAvailable = true
                        });
                });

            modelBuilder.Entity("_413Project2.Models.AppointmentInfo", b =>
                {
                    b.HasOne("_413Project2.Models.TimeSlots", "TimeSlots")
                        .WithMany()
                        .HasForeignKey("TimeSlotsTimeSlotId");
                });
#pragma warning restore 612, 618
        }
    }
}
